### ISSUE TITLE
can i use this build pep?

### ISSUE THREAD

**Issue by adontoo** [dttzyjw0012/device_xiaomi_mayfly#1]
Or which rom can build with this ? If it worked , I want to change some thing from this to build for my device. Thanks

**Comment by dttzyjw0012** [comment]
This device tree is a experimental work for PE12 and under development, so it cannot build any rom now. PEP's device and kernel is a little different from PE, so you need do some changes even it will be developed completed in the future.

**Comment by dttzyjw0012** [comment]
It is completed.
